version: '2'
services:
  web:
    build: .
    command: node main.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
        HOST: ${HOST}
        PORT: ${PORT}
        PG_HOST: host.docker.internal
        PG_PORT: ${PG_PORT}
        PG_DATABASE: ${PG_DATABASE}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}